### POST /subscriptions
POST http://localhost:8080/webhook
Content-Type: application/json

{
    "update_id": 123, 
    "message": {
        "message_id": 234,
        "chat": {
            "id": 345
        },
        "text": "/subscriptions"
    }
}

### POST /subscribe 228
POST http://localhost:8080/webhook
Content-Type: application/json

{
    "update_id": 123,
    "message": {
        "message_id": 234,
        "chat": {
            "id": 345
        },
        "text": "/subscribe"
    }
}


### POST 228
POST http://localhost:8080/webhook
Content-Type: application/json

{
    "update_id": 123,
    "message": {
        "message_id": 234,
        "chat": {
            "id": 345
        },
        "text": "228"
    }
}

###GET 404
GET http://localhost:8080/not_found

### Get metrics
GET http://localhost:8090/metrics